from functools import partial
from baselines.unet import UNet
from baselines.unet import UNetTransfomer

unet:
    model_class: UNet
    model_config:
        in_channels: 12 * 8
        n_classes: 6 * 8
        depth: 5
        wf: 6
        padding: True
        up_mode: "upconv"
        batch_norm: True
    dataset_config:
        transform: partial(UNetTransfomer.unet_pre_transform, stack_channels_on_time=True, zeropad2d=(6, 6, 1, 0), batch_dim=False)
    pre_transform: partial(UNetTransfomer.unet_pre_transform, stack_channels_on_time=True, zeropad2d=(6, 6, 1, 0), batch_dim=True, from_numpy=True)
    post_transform: partial(UNetTransfomer.unet_post_transform, stack_channels_on_time=True, crop=(6, 6, 1, 0), batch_dim=True)

# Can't find anything to calling python functions within YAML file
# This might justify sticking to a python file with dictionary
# although less readable
